manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/pashutk/zmk/tree/nrf52833
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
